query {
	products(
		first: 10
		query: "product_type:'custom_design_pricing'"
		sortKey: PRICE
	) {
		edges {
			node {
				id
				title
				priceRange {
					maxVariantPrice {
						amount
						currencyCode
					}
				}
				variants(first: 10) {
					edges {
						node {
							id
						}
					}
				}
				description
				descriptionHtml
				handle
				availableForSale
				productType
				publishedAt
				tags
				vendor
				images(first: 10) {
					edges {
						node {
							id
							originalSrc
							altText
							transformedSrc
						}
					}
				}
			}
		}
	}
}
